-- CATEGORÍAS
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Acción');
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Aventura');
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('RPG');
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Deportes');
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Carreras');

-- VIDEOJUEGOS
INSERT INTO VIDEOJUEGOS (TITULO, DESCRIPCION, FECHA_LANZAMIENTO, IMAGEN, ID_CATEGORIA)
VALUES (
'Grand Theft Auto V',
'Videojuego de acción y mundo abierto.',
TO_DATE('2013-09-17','YYYY-MM-DD'),
'gta5.jpg',
1
);

INSERT INTO VIDEOJUEGOS (TITULO, DESCRIPCION, FECHA_LANZAMIENTO, IMAGEN, ID_CATEGORIA)
VALUES (
'EA Sports FC 25',
'Videojuego de fútbol.',
TO_DATE('2024-09-27','YYYY-MM-DD'),
'fc25.jpg',
4
);

INSERT INTO VIDEOJUEGOS (TITULO, DESCRIPCION, FECHA_LANZAMIENTO, IMAGEN, ID_CATEGORIA)
VALUES (
'Minecraft',
'Juego de construcción y supervivencia.',
TO_DATE('2011-11-18','YYYY-MM-DD'),
'minecraft.jpg',
2
);

COMMIT;